name: Poc-test
author: greenit-centrale
version: 1
description: Defined test scenario for used in Green Coding Berlin automated tests.

services:
  Small_load_Container:
    image: python:3.10-slim
    ports:
      - 8083:5000
    setup-commands:
      - pip install --upgrade pip
      - pip install flask gevent gevent-websocket flask-socketio pexpect regex

flow:      
  - name: Launching app
    container: Small_load_Container
    commands:
      - type: console
        command: python3 /tmp/repo/flask-api/app.py
        detach: true
        note: Running app
